version: '3.7'

services:    
  postgres:
    image: kartoza/postgis:14-3.2--v2022.02.14
    restart: always
    ports:
      - '${POSTGRESQL_EXPOSED_PORT}:5432'
    volumes:
      - postgres:/data/postgres
    env_file:
      - .postgresql.env
    networks:
      - postgres

networks:
  postgres:
    driver: bridge

volumes:
  postgres: