version: '3'
services:
  web:
    build: web/
    ports:
      - "${WEB_PORT}:3000"
    volumes:
      - ./.env:/app/.env:ro
    env_file:
      - .env
    depends_on:
      - api

  api:
    build: api/
    ports:
      - "${API_PORT}:3001"
    volumes:
      - ./.env:/app/.env:ro
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgis/postgis:13-master
    restart: always
    env_file:
      - .env
    command: ["postgres", "-c", "log_statement=all"]
    volumes:
      - ./db:/var/lib/postgresql/data:rw
    # ports:
    #   - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5