version: '3'
services:
  web:
    # build: web/
    image: helpbuttons/helpbuttons-web:main
    ports:
      - "3000:3000"
    depends_on:
      - api
    networks:
      - web
      - api

  api:
    # build: api/
    image: helpbuttons/helpbuttons-api:main
    volumes:
      - config:/app/config/:rw
      - uploads:/app/uploads
    depends_on:
      - db
    networks:
      - api
      - db

  db:
    # build: postgres/
    image: helpbuttons/helpbuttons-psql:main
    restart: always
    command: ["postgres", "-c", "log_statement=all"]
    env_file:
      - env.db
    volumes:
      - db:/var/lib/postgresql/data:rw
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - db  
    #uncomment if using docker-compose up db and yarn dev for backend and not docker-compose.dev
    ports: 
      - 5432:5432

networks:
  web:
  api:
    internal: true
  db:
    internal: true

volumes:
  db:
  uploads:
  config:
