version: '3'
services:
  hb-front:
    build: frontend/
    ports:
      - 9003:3000
    env_file:
      - .env

### BACKEND

  hb-back:
    build: backend/
    ports:
      - ${BACKEND_PORT}:3001
    env_file:
      - .env
  db:
    image: postgis/postgis:13-master
    restart: always
    env_file:
      - .env
    container_name: helpbuttons_postgres
    command: ["postgres", "-c", "log_statement=all"]
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - ./db:/var/lib/postgresql/data:rw
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  # minio:
  #   image: quay.io/minio/minio:RELEASE.2022-06-07T00-33-41Z
  #   command: server /data --console-address ":9001"
  #   ports:
  #     - 9000:9000
  #     - 9001:9001
  #   environment:
  #     MINIO_ROOT_USER: minioadmin
  #     MINIO_ROOT_PASSWORD: minioadmin
  #   healthcheck:
  #     test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
  #     interval: 30s
  #     timeout: 20s
  #     retries: 3  hb-back:
    build: ./
    ports:
      - ${BACKEND_PORT}:3001
    env_file:
      - .env
  db:
    image: postgis/postgis:13-master
    restart: always
    env_file:
      - .env
    container_name: helpbuttons_postgres
    command: ["postgres", "-c", "log_statement=all"]
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - ./db:/var/lib/postgresql/data:rw
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  # minio:
  #   image: quay.io/minio/minio:RELEASE.2022-06-07T00-33-41Z
  #   command: server /data --console-address ":9001"
  #   ports:
  #     - 9000:9000
  #     - 9001:9001
  #   environment:
  #     MINIO_ROOT_USER: minioadmin
  #     MINIO_ROOT_PASSWORD: minioadmin
  #   healthcheck:
  #     test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
  #     interval: 30s
  #     timeout: 20s
  #     retries: 3