version: '3'
services:
  web:
#    build: web/
    image: helpbuttons/helpbuttons-web:main
    ports:
      - "3000:3000"
    depends_on:
      - api
    networks:
      - web
      - api

  api:
#    build: api/
    image: helpbuttons/helpbuttons-api:main
    volumes:
      - config:/app/config/:rw
      - uploads:/app/uploads
    depends_on:
      - db
    networks:
      - api
      - db

  db:
    image: postgis/postgis:13-master
    restart: always
    command: ["postgres", "-c", "log_statement=all"]
    env_file:
      - env.db
    volumes:
      - db:/var/lib/postgresql/data:rw
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - db

networks:
  web:
    external: true
  api:
  db:


volumes:
  db:
  uploads:
  config: