version: '3'
services:
  db:
    image: postgis/postgis:13-master
    restart: always
    env_file:
      - .env
    container_name: helpbuttons_postgres
    command: ["postgres", "-c", "log_statement=all"]
    ports:
      - ${POSTGRESQL_EXPOSED_PORT}:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
