version: '3'
services:
  web:
    build: web/
    image: helpbuttons/helpbuttons-web:main
    ports:
      - "3000:3000"
    depends_on:
      - api

  api:
    build: api/
    image: helpbuttons/helpbuttons-api:main
    volumes:
      - ./config.json:/app/config.json
      - ./uploads:/app/uploads
    depends_on:
      - db
#    ports:
#      - "3001:3001"

  db:
    image: postgis/postgis:13-master
    restart: always
    command: ["postgres", "-c", "log_statement=all"]
    env_file:
      - env.db
    volumes:
      - ./db:/var/lib/postgresql/data:rw
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
