name: ci 
on:
  push:
    branches: 
      - develop
  pull_request:
    branches:
      - develop
jobs:
  runNpmTarget:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run tests
      uses: anna-money/github-actions-npm@v2
      with:
        target: 'test'