name: ci-test
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: docker-compose up -d postgres
      - run: npm i
      - run: docker-compose exec postgres /migrations/run_all.sh reset
      - run: npm test
