name: ci-test
on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "checkout"
        uses: actions/checkout@v2
      - name: "copy env.ci to .env"
        run: |
          cp env.ci .env
      - name: "setup node"
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: "start postgis"
        run: |
         docker-compose -f docker-compose.tests.yml up -d db 
      - name: "run the tests"
        run: |
         docker-compose -f docker-compose.tests.yml up tests 
